### ISSUE TITLE
ZAFU_DDUP失效

### ISSUE THREAD

**Issue by yxh0** [Debuffxb/ZAFU_DDUP#2]
错误返回结果json如下：
```json
{
	"errorCode": -1,
	"errorMessage": "user code exception caught",
	"requestId": "f888fdaf-903c-45f5-a8a4-b6e6fa6ffad9",
	"stackTrace": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)\n    at TLSSocket.emit (events.js:311:20)\n    at TLSSocket._finishInit (_tls_wrap.js:916:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)",
	"statusCode": 430
}
```

**Comment by Debuffxb** [comment]
{"type":"error","code":"非法请求，已经记录请求信息，一切法律后果自负！","content":"非法请求，已经记录请求信息，一切法律后果自负！","anchor":"undefined","errorFields":[],"data":null}
